### PR TITLE
Correct some warning and BananaPI compilation issue

### PR DESCRIPTION
**Pull request by destroyedlolo**
Hi,

I did several "cleaning" : 
- removing compilation warning
- allow a smooth compilation on BananaPI
- avoid automatic installation in /usr/local

Bye

### CODE REVIEW

**Review by jonesman — APPROVED** [review]

**Review by jonesman — APPROVED** [review]

**Review by jonesman — APPROVED** [review]

**Review by jonesman — APPROVED** [review]

**Review by jonesman — CHANGES_REQUESTED** [review]
As "I2C_DEV" was supposed to be configured by whoever is using it, I think it would be more clear to just leave it as-is. Maybe a comment would work better, saying that on the BananaPI the default I2C device is i2c-2 ?

**Comment by jonesman** [comment]
Hi, thank you very much for the pull request and your fixes/additions!
There was one thing in there that i think would be better left unchanged. i tried approving/commenting on the individual commits but I guess that's not how it works :)

**Comment by destroyedlolo** [comment]
I 'm not so sure as the Banana is already a target of the deployment chain.
In such case, just selecting BananaPI in autogen.sh will do all the work without any modification.

Anyway, I'm working on another version on which the device will be provided as argument : The BananaPro and I think some Raspberries have 2 user serviceable I2C buses, so it will allow to have 2 LCD connected at the same time ... and makes the library totally platform agnostic.
But I don't think I'll propose it to be merged as I have no way to test provided examples but the simple oled_demo.

Bye

**Comment by jonesman** [comment]
Yeah that does sound like a very good idea, i had thrown this together very quickly when i found the original library, and just wanted to see things working. Then threw it on here so it could be found,
but never touched it again.
I'd be happy to have your changes if you feel like it, but thanks for bringing it up anyways!

**Comment by destroyedlolo** [comment]
Hi Jonas,
It's a bit late for me ... but it's working : no reference anymore to the target platform :)It was a bit tedious as the includes and Makefiles miss some dependencies creating random result if I forget to remove previous objects during my attempts but it should be almost corrected now.
Next will be to add it inside my dashboard framework (named Selene), yeahhh.
Best regards,
Laurent
 

    Le dimanche 23 décembre 2018 à 20:15:56 UTC+1, Jonas Keunecke <notifications@github.com> a écrit :  
 
 
Yeah that does sound like a very good idea, i had thrown this together very quickly when i found the original library, and just wanted to see things working. Then threw it on here so it could be found,
but never touched it again.
I'd be happy to have your changes if you feel like it, but thanks for bringing it up anyways!

**Comment by jonesman** [comment]
Hi Laurent,

that's great to hear, and does sound a bit messy, I might take a look later to see what you mean :)
That framework does sound cool too, i'll try to remember that if I ever end up putting in any automation stuff/devices over here!
Enjoy the Holidays, I think I'll try to get into some coding myself, was just looking up Selenium (weirdly enough) bindings for Perl.

Cheers, Jon

**Pull request merged**
